# 🤖 Dependabot Configuration for Otogram
# Automated dependency updates for security and maintenance

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "dygje"
    assignees:
      - "dygje"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ dev"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Group related updates
    groups:
      telegram-deps:
        patterns:
          - "pyrofork*"
          - "python-telegram-bot*"
          - "TgCrypto*"
      database-deps:
        patterns:
          - "motor*"
          - "pymongo*"
      dev-deps:
        patterns:
          - "pytest*"
          - "black*"
          - "isort*"
          - "mypy*"
          - "pre-commit*"
      security-deps:
        patterns:
          - "cryptography*"
          - "pycryptodome*"
    # Auto-merge minor updates for trusted packages
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "direct"
        update-type: "version-update:semver-minor"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "dygje"
    assignees:
      - "dygje"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      core-actions:
        patterns:
          - "actions/*"
          - "github/codeql-action*"