version: 2
updates:
  # Python dependencies - monthly updates untuk menghindari terlalu banyak PR
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 2  # Batasi PR yang terbuka
    commit-message:
      prefix: "deps(pip)"
      include: "scope"
    reviewers:
      - "dygje"
    # Kelompokkan update minor dan patch
    groups:
      telegram-deps:
        patterns:
          - "python-telegram-bot*"
          - "pyrofork*"
          - "TgCrypto*"
      database-deps:
        patterns:
          - "motor*"
          - "pymongo*"
      core-deps:
        patterns:
          - "pydantic*"
          - "loguru*"
          - "python-dotenv*"

  # GitHub Actions - setiap 3 bulan
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci(actions)"
      include: "scope"

  # Docker - setiap 3 bulan  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "docker"
      include: "scope"