version: 2
updates:
  # Python dependencies - weekly updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "dygje"

  # GitHub Actions - monthly updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker - monthly updates  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "docker"
      include: "scope"