# 💖 Funding Information for Otogram
# Support the development of this Telegram automation system

# GitHub Sponsors
github: [dygje]

# Custom funding URLs
custom: [
  'https://github.com/sponsors/dygje'
]