# MkDocs Configuration for Telegram Automation System
site_name: Telegram Automation System
site_description: Professional Telegram automation system with mass messaging and bot management
site_author: Telegram Automation System Contributors
site_url: https://dygje.github.io/Otogram

# Repository
repo_name: dygje/Otogram
repo_url: https://github.com/dygje/Otogram
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  
  # Color scheme
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Features
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
  
  # Icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  
  # Logo and favicon
  logo: assets/logo.png
  favicon: assets/favicon.ico

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - First Run: getting-started/first-run.md
  - User Guide:
    - Bot Commands: user-guide/bot-commands.md
    - Message Management: user-guide/messages.md
    - Group Management: user-guide/groups.md
    - System Configuration: user-guide/configuration.md
    - Monitoring: user-guide/monitoring.md
  - API Reference:
    - Overview: api/overview.md
    - Models: api/models.md
    - Services: api/services.md
    - Core: api/core.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md
    - Security: about/security.md

# Plugins
plugins:
  - search:
      lang: en
  - mermaid2:
      arguments:
        theme: neutral
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - def_list
  - footnotes
  - md_in_html
  
  # Python Markdown Extensions  
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # Admonitions
  - admonition
  - pymdownx.details

# Extra CSS and JS
extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js

# Extra variables
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/dygje/Otogram
      name: GitHub Repository
    - icon: fontawesome/solid/bug
      link: https://github.com/dygje/Otogram/issues
      name: Report Issues

# Copyright
copyright: Copyright &copy; 2024 Telegram Automation System Contributors

# Analytics (if needed)
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto