# Ruff configuration file
target-version = "py311"
line-length = 100

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
    "PLR", # pylint refactor
    "PLE", # pylint errors
    "PLW", # pylint warnings
    "RUF", # ruff-specific rules
]

ignore = [
    "E501",     # line too long, handled by formatter
    "B008",     # do not perform function calls in argument defaults
    "C901",     # too complex
    "PLR0913",  # too many arguments
    "PLR0912",  # too many branches
    "PLR0915",  # too many statements
]

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    ".env",
    "migrations",
]

[lint.per-file-ignores]
"tests/*" = ["ARG", "S101"]
"scripts/*" = ["PLR0913"]

[lint.isort]
known-first-party = ["src"]