blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/telegram-automation-system/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/your-org/telegram-automation-system/tree/main/docs
    about: Check our documentation for setup guides and API reference
  - name: 🩺 Health Check
    url: https://github.com/your-org/telegram-automation-system/blob/main/scripts/health_check.py
    about: Run system diagnostics before reporting issues